ZIP 212 NCC fixes
zcash/zcash pull request #4674
Opened 2020-08-19 06:35 UTC by therealyingtong

Fixes to the ZIP 212 implementation as suggested in the NCC audit.

2020-08-19 23:24 UTC, str4d requested changes
utACK after renaming.

2020-08-19 23:24 UTC, str4d commented on src/zcash/prf.h
> +const char PRF_ESK_DIVERSIFIER = 5;
"Diversifier" conflates these with diversifiers in the Sapling protocol. The protocol spec uses the symbol `t` for these, which I think means "tag", so:
```suggestion
const char PRF_ASK_TAG = 0;
const char PRF_NSK_TAG = 1;
const char PRF_OVK_TAG = 2;
const char PRF_RCM_TAG = 4;
const char PRF_ESK_TAG = 5;
```

2020-08-20 12:08 UTC, str4d approved these changes
utACK

2020-08-20 13:08 UTC, nuttycom commented
utACK

2020-08-20 15:05 UTC, therealyingtong commented
@zkbot r+

2020-08-20 17:07 UTC, merged