Update LevelDB to upstream commit f545dfabf
zcash/zcash pull request #4739
Opened 2020-09-22 23:19 UTC by str4d

Cherry-picked from the following upstream PRs:

- bitcoin/bitcoin#7911
- bitcoin/bitcoin#7982
- bitcoin/bitcoin#8133
- bitcoin/bitcoin#8784
  - Only the missing changes.
- bitcoin/bitcoin#8826
- bitcoin/bitcoin#8613
- bitcoin/bitcoin#10544
- bitcoin/bitcoin#10633
  - Only the changes to files and code we have.
- bitcoin/bitcoin#10806
- bitcoin/bitcoin#10958
- bitcoin/bitcoin#12451
- bitcoin/bitcoin#13925
- bitcoin/bitcoin#15270

This upgrades LevelDB in the exact same commit progression as upstream, up to January 2019.

2020-09-22 23:20 UTC, str4d commented
@zkbot try

2020-09-22 23:23 UTC, str4d commented
There will be a second PR after this one to update LevelDB to match what Bitcoin Core currently uses, but that final migration in https://github.com/bitcoin/bitcoin/pull/17398 is quite large, so I figured I'd land these changes first.

2020-09-23 00:44 UTC, str4d commented
Looks like there was a single transient failure in an otherwise successful CI run.

2020-09-23 09:08 UTC, daira commented
Will review this today.

2020-09-25 11:38 UTC, rex4539 requested changes

2020-09-25 11:38 UTC, rex4539 commented on src/leveldb/db/db_bench.cc
> +// Approximate size of user data packed per block (before compression.
```suggestion
// Approximate size of user data packed per block (before compression).
```

2020-09-25 14:20 UTC, daira approved these changes
ACK with minor comments.

2020-09-25 14:20 UTC, daira commented on src/leveldb/port/port_win.h
>  #include <string>
Add below `#include <stdint.h>`:
```
static_assert(sizeof(ssize_t) == sizeof(size_t), "ssize_t should be the same size as size_t");
```

2020-09-25 15:03 UTC, str4d commented
@zkbot r+

2020-09-25 17:32 UTC, merged