depends: Move to Clang 9.0.1
zcash/zcash pull request #4806
Opened 2020-10-22 13:33 UTC by str4d

Closes #4801.

2020-10-25 04:49 UTC, rex4539 commented
Compiles fine on native macOS and all tests pass.

2020-12-18 06:08 UTC, rex4539 requested changes
Wrong branch. Ignore.

2020-12-18 06:20 UTC, rex4539 approved these changes
ACK https://github.com/zcash/zcash/commit/5a45f31b4194fa6c6989b330f5502d3fe5fbaf79 on native macOS.

2021-01-15 19:24 UTC, str4d commented
Confirmed that once #4950 merges, we can jump straight to Clang 11 and everything builds on Ubuntu 20.04. So I'm going to close this and open a Clang 11 PR.

2021-01-15 19:24 UTC, closed without merging