Replace boost::variant and boost::optional with standard library
zcash/zcash pull request #4892
Opened 2020-12-04 02:55 UTC by str4d

Closes #4821. Closes #4822.

2020-12-04 03:15 UTC, str4d commented
@zkbot try

2020-12-07 22:30 UTC, rex4539 commented
```
  CXX      gtest/zcash_gtest-test_consensus.o
gtest/test_consensus.cpp:24:9: error: use of undeclared identifier 'librustzcash_zebra_crypto_sign_verify_detached'
        librustzcash_zebra_crypto_sign_verify_detached(
        ^
gtest/test_consensus.cpp:23:5: error: no type named 'Compare' in the global namespace
    EXPECT_EQ(
    ^~~~~~~~~~
/Users/rex/rex4539-zcash-ed25519-zebra-consensus/depends/x86_64-apple-darwin20.2.0/share/../include/gtest/gtest.h:1968:63: note: expanded from macro 'EXPECT_EQ'
                      EqHelper<GTEST_IS_NULL_LITERAL_(val1)>::Compare, \
                                                            ~~^
/Users/rex/rex4539-zcash-ed25519-zebra-consensus/depends/x86_64-apple-darwin20.2.0/share/../include/gtest/gtest_pred_impl.h:161:23: note: expanded from macro 'EXPECT_PRED_FORMAT2'
  GTEST_PRED_FORMAT2_(pred_format, v1, v2, GTEST_NONFATAL_FAILURE_)
                      ^~~~~~~~~~~
/Users/rex/rex4539-zcash-ed25519-zebra-consensus/depends/x86_64-apple-darwin20.2.0/share/../include/gtest/gtest_pred_impl.h:146:17: note: expanded from macro 'GTEST_PRED_FORMAT2_'
  GTEST_ASSERT_(pred_format(#v1, #v2, v1, v2), \
                ^~~~~~~~~~~
/Users/rex/rex4539-zcash-ed25519-zebra-consensus/depends/x86_64-apple-darwin20.2.0/share/../include/gtest/gtest_pred_impl.h:76:52: note: expanded from macro 'GTEST_ASSERT_'
  if (const ::testing::AssertionResult gtest_ar = (expression)) \
                                                   ^~~~~~~~~~
gtest/test_consensus.cpp:23:5: error: expected ')'
/Users/rex/rex4539-zcash-ed25519-zebra-consensus/depends/x86_64-apple-darwin20.2.0/share/../include/gtest/gtest.h:1967:3: note: expanded from macro 'EXPECT_EQ'
  EXPECT_PRED_FORMAT2(::testing::internal:: \
  ^
/Users/rex/rex4539-zcash-ed25519-zebra-consensus/depends/x86_64-apple-darwin20.2.0/share/../include/gtest/gtest_pred_impl.h:161:3: note: expanded from macro 'EXPECT_PRED_FORMAT2'
  GTEST_PRED_FORMAT2_(pred_format, v1, v2, GTEST_NONFATAL_FAILURE_)
  ^
/Users/rex/rex4539-zcash-ed25519-zebra-consensus/depends/x86_64-apple-darwin20.2.0/share/../include/gtest/gtest_pred_impl.h:146:29: note: expanded from macro 'GTEST_PRED_FORMAT2_'
  GTEST_ASSERT_(pred_format(#v1, #v2, v1, v2), \
                            ^
<scratch space>:12:1: note: expanded from here
"librustzcash_zebra_crypto_sign_verify_detached( sig.data(), (const unsigned char*)msg.data(), msg.size(), pubkey.data())"
^
gtest/test_consensus.cpp:23:5: note: to match this '('
/Users/rex/rex4539-zcash-ed25519-zebra-consensus/depends/x86_64-apple-darwin20.2.0/share/../include/gtest/gtest.h:1967:3: note: expanded from macro 'EXPECT_EQ'
  EXPECT_PRED_FORMAT2(::testing::internal:: \
  ^
/Users/rex/rex4539-zcash-ed25519-zebra-consensus/depends/x86_64-apple-darwin20.2.0/share/../include/gtest/gtest_pred_impl.h:161:3: note: expanded from macro 'EXPECT_PRED_FORMAT2'
  GTEST_PRED_FORMAT2_(pred_format, v1, v2, GTEST_NONFATAL_FAILURE_)
  ^
/Users/rex/rex4539-zcash-ed25519-zebra-consensus/depends/x86_64-apple-darwin20.2.0/share/../include/gtest/gtest_pred_impl.h:146:28: note: expanded from macro 'GTEST_PRED_FORMAT2_'
  GTEST_ASSERT_(pred_format(#v1, #v2, v1, v2), \
                           ^
gtest/test_consensus.cpp:62:9: error: use of undeclared identifier 'librustzcash_zebra_crypto_sign_verify_detached'
        librustzcash_zebra_crypto_sign_verify_detached(
        ^
gtest/test_consensus.cpp:61:5: error: no type named 'Compare' in the global namespace
    EXPECT_EQ(
    ^~~~~~~~~~
/Users/rex/rex4539-zcash-ed25519-zebra-consensus/depends/x86_64-apple-darwin20.2.0/share/../include/gtest/gtest.h:1968:63: note: expanded from macro 'EXPECT_EQ'
                      EqHelper<GTEST_IS_NULL_LITERAL_(val1)>::Compare, \
                                                            ~~^
/Users/rex/rex4539-zcash-ed25519-zebra-consensus/depends/x86_64-apple-darwin20.2.0/share/../include/gtest/gtest_pred_impl.h:161:23: note: expanded from macro 'EXPECT_PRED_FORMAT2'
  GTEST_PRED_FORMAT2_(pred_format, v1, v2, GTEST_NONFATAL_FAILURE_)
                      ^~~~~~~~~~~
/Users/rex/rex4539-zcash-ed25519-zebra-consensus/depends/x86_64-apple-darwin20.2.0/share/../include/gtest/gtest_pred_impl.h:146:17: note: expanded from macro 'GTEST_PRED_FORMAT2_'
  GTEST_ASSERT_(pred_format(#v1, #v2, v1, v2), \
                ^~~~~~~~~~~
/Users/rex/rex4539-zcash-ed25519-zebra-consensus/depends/x86_64-apple-darwin20.2.0/share/../include/gtest/gtest_pred_impl.h:76:52: note: expanded from macro 'GTEST_ASSERT_'
  if (const ::testing::AssertionResult gtest_ar = (expression)) \
                                                   ^~~~~~~~~~
gtest/test_consensus.cpp:61:5: error: expected ')'
/Users/rex/rex4539-zcash-ed25519-zebra-consensus/depends/x86_64-apple-darwin20.2.0/share/../include/gtest/gtest.h:1967:3: note: expanded from macro 'EXPECT_EQ'
  EXPECT_PRED_FORMAT2(::testing::internal:: \
  ^
/Users/rex/rex4539-zcash-ed25519-zebra-consensus/depends/x86_64-apple-darwin20.2.0/share/../include/gtest/gtest_pred_impl.h:161:3: note: expanded from macro 'EXPECT_PRED_FORMAT2'
  GTEST_PRED_FORMAT2_(pred_format, v1, v2, GTEST_NONFATAL_FAILURE_)
  ^
/Users/rex/rex4539-zcash-ed25519-zebra-consensus/depends/x86_64-apple-darwin20.2.0/share/../include/gtest/gtest_pred_impl.h:146:29: note: expanded from macro 'GTEST_PRED_FORMAT2_'
  GTEST_ASSERT_(pred_format(#v1, #v2, v1, v2), \
                            ^
<scratch space>:20:1: note: expanded from here
"librustzcash_zebra_crypto_sign_verify_detached( sig_hex.data(), (const unsigned char*)msg.data(), msg.size(), pubkey_hex.data())"
^
gtest/test_consensus.cpp:61:5: note: to match this '('
/Users/rex/rex4539-zcash-ed25519-zebra-consensus/depends/x86_64-apple-darwin20.2.0/share/../include/gtest/gtest.h:1967:3: note: expanded from macro 'EXPECT_EQ'
  EXPECT_PRED_FORMAT2(::testing::internal:: \
  ^
/Users/rex/rex4539-zcash-ed25519-zebra-consensus/depends/x86_64-apple-darwin20.2.0/share/../include/gtest/gtest_pred_impl.h:161:3: note: expanded from macro 'EXPECT_PRED_FORMAT2'
  GTEST_PRED_FORMAT2_(pred_format, v1, v2, GTEST_NONFATAL_FAILURE_)
  ^
/Users/rex/rex4539-zcash-ed25519-zebra-consensus/depends/x86_64-apple-darwin20.2.0/share/../include/gtest/gtest_pred_impl.h:146:28: note: expanded from macro 'GTEST_PRED_FORMAT2_'
  GTEST_ASSERT_(pred_format(#v1, #v2, v1, v2), \
                           ^
6 errors generated.
make[2]: *** [gtest/zcash_gtest-test_consensus.o] Error 1
```

2020-12-07 22:54 UTC, rex4539 requested changes
Ignore this. Wrong post.

2020-12-07 22:56 UTC, rex4539 approved these changes

2020-12-07 23:21 UTC, rex4539 requested changes
```
CXX      libbitcoin_server_a-timedata.o
pow.cpp:34:83: error: 'value' is unavailable: introduced in macOS 10.14
            pindexLast->nHeight >= params.nPowAllowMinDifficultyBlocksAfterHeight.value())
                                                                                  ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/optional:944:33: note: 'value' has been explicitly marked unavailable here
    constexpr value_type const& value() const&
                                ^
1 error generated.
make[2]: *** [libbitcoin_server_a-pow.o] Error 1
make[2]: *** Waiting for unfinished jobs....
metrics.cpp:283:28: error: 'value' is unavailable: introduced in macOS 10.14
        return (nextHeight.value() - currentHeight) * params.PoWTargetSpacing(nextHeight.value() - 1);
                           ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/optional:953:27: note: 'value' has been explicitly marked unavailable here
    constexpr value_type& value() &
                          ^
metrics.cpp:283:90: error: 'value' is unavailable: introduced in macOS 10.14
        return (nextHeight.value() - currentHeight) * params.PoWTargetSpacing(nextHeight.value() - 1);
                                                                                         ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/optional:953:27: note: 'value' has been explicitly marked unavailable here
    constexpr value_type& value() &
                          ^
metrics.cpp:383:70: error: 'value' is unavailable: introduced in macOS 10.14
        auto nextHeight = NextActivationHeight(stats.height, params).value();
                                                                     ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/optional:962:28: note: 'value' has been explicitly marked unavailable here
    constexpr value_type&& value() &&
                           ^
metrics.cpp:384:59: error: 'value' is unavailable: introduced in macOS 10.14
        auto nextBranch = NextEpoch(stats.height, params).value();
                                                          ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/optional:962:28: note: 'value' has been explicitly marked unavailable here
    constexpr value_type&& value() &&
                           ^
metrics.cpp:386:116: error: 'value' is unavailable: introduced in macOS 10.14
                                   NetworkUpgradeInfo[nextBranch].strName, nextHeight, DisplayDuration(secondsLeft.value(), DurationFormat::REDUCED));
                                                                                                                   ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/optional:953:27: note: 'value' has been explicitly marked unavailable here
    constexpr value_type& value() &
                          ^
metrics.cpp:663:46: error: 'value' is unavailable: introduced in macOS 10.14
            lines += printStats(metricsStats.value(), isScreen, mining);
                                             ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/optional:953:27: note: 'value' has been explicitly marked unavailable here
    constexpr value_type& value() &
                          ^
6 errors generated.
make[2]: *** [libbitcoin_server_a-metrics.o] Error 1
miner.cpp:140:49: error: 'value' is unavailable: introduced in macOS 10.14
            mtx.vShieldedOutput.push_back(odesc.value());
                                                ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/optional:953:27: note: 'value' has been explicitly marked unavailable here
    constexpr value_type& value() &
                          ^
miner.cpp:191:39: error: 'visit<AddFundingStreamValueToTx, std::__1::variant<libzcash::SaplingPaymentAddress, CScript> &>' is unavailable: introduced in macOS 10.14
                    bool added = std::visit(AddFundingStreamValueToTx(mtx, ctx, fselem.second, GetZip212Flag()), fselem.first);
                                      ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/variant:1587:26: note: 'visit<AddFundingStreamValueToTx, std::__1::variant<libzcash::SaplingPaymentAddress, CScript> &>' has been explicitly marked unavailable here
constexpr decltype(auto) visit(_Visitor&& __visitor, _Vs&&... __vs) {
                         ^
miner.cpp:257:45: error: 'value' is unavailable: introduced in macOS 10.14
        mtx.vShieldedOutput.push_back(odesc.value());
                                            ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/optional:953:27: note: 'value' has been explicitly marked unavailable here
    constexpr value_type& value() &
                          ^
miner.cpp:578:14: error: 'visit<AddOutputsToCoinbaseTxAndSign, const std::__1::variant<InvalidMinerAddress, libzcash::SaplingPaymentAddress, boost::shared_ptr<CReserveScript> > &>' is unavailable: introduced in macOS 10.14
        std::visit(
             ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/variant:1587:26: note: 'visit<AddOutputsToCoinbaseTxAndSign, const std::__1::variant<InvalidMinerAddress, libzcash::SaplingPaymentAddress, boost::shared_ptr<CReserveScript> > &>' has been explicitly marked unavailable here
constexpr decltype(auto) visit(_Visitor&& __visitor, _Vs&&... __vs) {
                         ^
miner.cpp:651:29: error: 'get<CKeyID, CNoDestination, CKeyID, CScriptID>' is unavailable: introduced in macOS 10.14
        CKeyID keyID = std::get<CKeyID>(addr);
                            ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/variant:1429:16: note: 'get<CKeyID, CNoDestination, CKeyID, CScriptID>' has been explicitly marked unavailable here
constexpr _Tp& get(variant<_Types...>& __v) {
               ^
miner.cpp:660:37: error: 'get<libzcash::SaplingPaymentAddress, libzcash::InvalidEncoding, libzcash::SproutPaymentAddress, libzcash::SaplingPaymentAddress>' is unavailable: introduced in macOS 10.14
                minerAddress = std::get<libzcash::SaplingPaymentAddress>(zaddr);
                                    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/variant:1429:16: note: 'get<libzcash::SaplingPaymentAddress, libzcash::InvalidEncoding, libzcash::SproutPaymentAddress, libzcash::SaplingPaymentAddress>' has been explicitly marked unavailable here
constexpr _Tp& get(variant<_Types...>& __v) {
               ^
miner.cpp:741:19: error: 'visit<IsValidMinerAddress, std::__1::variant<InvalidMinerAddress, libzcash::SaplingPaymentAddress, boost::shared_ptr<CReserveScript> > &>' is unavailable: introduced in macOS 10.14
        if (!std::visit(IsValidMinerAddress(), minerAddress)) {
                  ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/variant:1587:26: note: 'visit<IsValidMinerAddress, std::__1::variant<InvalidMinerAddress, libzcash::SaplingPaymentAddress, boost::shared_ptr<CReserveScript> > &>' has been explicitly marked unavailable here
constexpr decltype(auto) visit(_Visitor&& __visitor, _Vs&&... __vs) {
                         ^
miner.cpp:836:26: error: 'visit<KeepMinerAddress, std::__1::variant<InvalidMinerAddress, libzcash::SaplingPaymentAddress, boost::shared_ptr<CReserveScript> > &>' is unavailable: introduced in macOS 10.14
                    std::visit(KeepMinerAddres [...]

2020-12-07 23:24 UTC, rex4539 commented on src/pow.cpp
> +            pindexLast->nHeight >= params.nPowAllowMinDifficultyBlocksAfterHeight.value())
```
pow.cpp:34:83: error: 'value' is unavailable: introduced in macOS 10.14
            pindexLast->nHeight >= params.nPowAllowMinDifficultyBlocksAfterHeight.value())
                                                                                  ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/optional:944:33: note: 'value' has been explicitly marked unavailable here
    constexpr value_type const& value() const&
                                ^
1 error generated.
```

2020-12-07 23:29 UTC, rex4539 commented on src/metrics.cpp
> +        return (nextHeight.value() - currentHeight) * params.PoWTargetSpacing(nextHeight.value() - 1);
```
metrics.cpp:283:28: error: 'value' is unavailable: introduced in macOS 10.14
        return (nextHeight.value() - currentHeight) * params.PoWTargetSpacing(nextHeight.value() - 1);
                           ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/optional:953:27: note: 'value' has been explicitly marked unavailable here
    constexpr value_type& value() &
                          ^
metrics.cpp:283:90: error: 'value' is unavailable: introduced in macOS 10.14
        return (nextHeight.value() - currentHeight) * params.PoWTargetSpacing(nextHeight.value() - 1);
                                                                                         ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/optional:953:27: note: 'value' has been explicitly marked unavailable here
    constexpr value_type& value() &
                          ^
```

2020-12-07 23:30 UTC, rex4539 commented on src/miner.cpp
> +            mtx.vShieldedOutput.push_back(odesc.value());
```
miner.cpp:140:49: error: 'value' is unavailable: introduced in macOS 10.14
            mtx.vShieldedOutput.push_back(odesc.value());
                                                ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/optional:953:27: note: 'value' has been explicitly marked unavailable here
    constexpr value_type& value() &
                          ^
```

2020-12-07 23:31 UTC, rex4539 commented on src/miner.cpp
> +                    bool added = std::visit(AddFundingStreamValueToTx(mtx, ctx, fselem.second, GetZip212Flag()), fselem.first);
```
miner.cpp:191:39: error: 'visit<AddFundingStreamValueToTx, std::__1::variant<libzcash::SaplingPaymentAddress, CScript> &>' is unavailable: introduced in macOS 10.14
                    bool added = std::visit(AddFundingStreamValueToTx(mtx, ctx, fselem.second, GetZip212Flag()), fselem.first);
                                      ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/variant:1587:26: note: 'visit<AddFundingStreamValueToTx, std::__1::variant<libzcash::SaplingPaymentAddress, CScript> &>' has been explicitly marked unavailable here
constexpr decltype(auto) visit(_Visitor&& __visitor, _Vs&&... __vs) {
                         ^
```

2020-12-07 23:32 UTC, rex4539 commented on src/miner.cpp
> +        mtx.vShieldedOutput.push_back(odesc.value());
```
miner.cpp:257:45: error: 'value' is unavailable: introduced in macOS 10.14
        mtx.vShieldedOutput.push_back(odesc.value());
                                            ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/optional:953:27: note: 'value' has been explicitly marked unavailable here
    constexpr value_type& value() &
                          ^
```

2020-12-07 23:32 UTC, rex4539 commented on src/miner.cpp
> +        std::visit(
```
miner.cpp:578:14: error: 'visit<AddOutputsToCoinbaseTxAndSign, const std::__1::variant<InvalidMinerAddress, libzcash::SaplingPaymentAddress, boost::shared_ptr<CReserveScript> > &>' is unavailable: introduced in macOS 10.14
        std::visit(
             ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/variant:1587:26: note: 'visit<AddOutputsToCoinbaseTxAndSign, const std::__1::variant<InvalidMinerAddress, libzcash::SaplingPaymentAddress, boost::shared_ptr<CReserveScript> > &>' has been explicitly marked unavailable here
constexpr decltype(auto) visit(_Visitor&& __visitor, _Vs&&... __vs) {
                         ^
```

2020-12-07 23:32 UTC, rex4539 commented on src/miner.cpp
> +        CKeyID keyID = std::get<CKeyID>(addr);
```
miner.cpp:651:29: error: 'get<CKeyID, CNoDestination, CKeyID, CScriptID>' is unavailable: introduced in macOS 10.14
        CKeyID keyID = std::get<CKeyID>(addr);
                            ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/variant:1429:16: note: 'get<CKeyID, CNoDestination, CKeyID, CScriptID>' has been explicitly marked unavailable here
constexpr _Tp& get(variant<_Types...>& __v) {
               ^
```

2020-12-07 23:33 UTC, rex4539 commented on src/miner.cpp
> +                minerAddress = std::get<libzcash::SaplingPaymentAddress>(zaddr);
```
miner.cpp:660:37: error: 'get<libzcash::SaplingPaymentAddress, libzcash::InvalidEncoding, libzcash::SproutPaymentAddress, libzcash::SaplingPaymentAddress>' is unavailable: introduced in macOS 10.14
                minerAddress = std::get<libzcash::SaplingPaymentAddress>(zaddr);
                                    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/variant:1429:16: note: 'get<libzcash::SaplingPaymentAddress, libzcash::InvalidEncoding, libzcash::SproutPaymentAddress, libzcash::SaplingPaymentAddress>' has been explicitly marked unavailable here
constexpr _Tp& get(variant<_Types...>& __v) {
               ^
```

2020-12-07 23:33 UTC, rex4539 commented on src/miner.cpp
> +        if (!std::visit(IsValidMinerAddress(), minerAddress)) {
```
miner.cpp:741:19: error: 'visit<IsValidMinerAddress, std::__1::variant<InvalidMinerAddress, libzcash::SaplingPaymentAddress, boost::shared_ptr<CReserveScript> > &>' is unavailable: introduced in macOS 10.14
        if (!std::visit(IsValidMinerAddress(), minerAddress)) {
                  ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/variant:1587:26: note: 'visit<IsValidMinerAddress, std::__1::variant<InvalidMinerAddress, libzcash::SaplingPaymentAddress, boost::shared_ptr<CReserveScript> > &>' has been explicitly marked unavailable here
constexpr decltype(auto) visit(_Visitor&& __visitor, _Vs&&... __vs) {
                         ^
```

2020-12-07 23:34 UTC, rex4539 commented on src/miner.cpp
> +                    std::visit(KeepMinerAddress(), minerAddress);
```
miner.cpp:836:26: error: 'visit<KeepMinerAddress, std::__1::variant<InvalidMinerAddress, libzcash::SaplingPaymentAddress, boost::shared_ptr<CReserveScript> > &>' is unavailable: introduced in macOS 10.14
                    std::visit(KeepMinerAddress(), minerAddress);
                         ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/variant:1587:26: note: 'visit<KeepMinerAddress, std::__1::variant<InvalidMinerAddress, libzcash::SaplingPaymentAddress, boost::shared_ptr<CReserveScript> > &>' has been explicitly marked unavailable here
constexpr decltype(auto) visit(_Visitor&& __visitor, _Vs&&... __vs) {
                         ^
```

2020-12-07 23:35 UTC, rex4539 commented on src/primitives/transaction.h
> +    std::visit(ps, proof);
```
./primitives/transaction.h:172:10: error: 'visit<SproutProofSerializer<OverrideStream<CSizeComputer> > &, const std::__1::variant<libzcash::PHGRProof, std::__1::array<unsigned char, 192> > &>' is unavailable: introduced in macOS 10.14
    std::visit(ps, proof);
         ^
./primitives/transaction.h:285:11: note: in instantiation of function template specialization 'SerReadWriteSproutProof<OverrideStream<CSizeComputer>, std::__1::variant<libzcash::PHGRProof, std::__1::array<unsigned char, 192> > >' requested here
        ::SerReadWriteSproutProof(s, proof, useGroth, ser_action);
          ^
./primitives/transaction.h:267:5: note: in instantiation of function template specialization 'JSDescription::SerializationOp<OverrideStream<CSizeComputer>, CSerActionSerialize>' requested here
    ADD_SERIALIZE_METHODS;
    ^
./serialize.h:209:27: note: expanded from macro 'ADD_SERIALIZE_METHODS'
        NCONST_PTR(this)->SerializationOp(s, CSerActionSerialize());  \
                          ^
./serialize.h:612:7: note: in instantiation of function template specialization 'JSDescription::Serialize<OverrideStream<CSizeComputer> >' requested here
    a.Serialize(os);
      ^
./serialize.h:731:11: note: in instantiation of function template specialization 'Serialize<OverrideStream<CSizeComputer>, JSDescription>' requested here
        ::Serialize(os, (*vi));
          ^
./serialize.h:737:5: note: in instantiation of function template specialization 'Serialize_impl<OverrideStream<CSizeComputer>, JSDescription, std::__1::allocator<JSDescription>, JSDescription>' requested here
    Serialize_impl(os, v, T());
    ^
./serialize.h:1040:7: note: (skipping 2 contexts in backtrace; use -ftemplate-backtrace-limit=0 to see all)
    ::Serialize(s, obj);
      ^
./primitives/transaction.h:571:5: note: in instantiation of function template specialization 'CTransaction::SerializationOp<CSizeComputer, CSerActionSerialize>' requested here
    ADD_SERIALIZE_METHODS;
    ^
./serialize.h:209:27: note: expanded from macro 'ADD_SERIALIZE_METHODS'
        NCONST_PTR(this)->SerializationOp(s, CSerActionSerialize());  \
                          ^
./serialize.h:612:7: note: in instantiation of function template specialization 'CTransaction::Serialize<CSizeComputer>' requested here
    a.Serialize(os);
      ^
./serialize.h:1092:11: note: in instantiation of function template specialization 'Serialize<CSizeComputer, CTransaction>' requested here
        ::Serialize(*this, obj);
          ^
./serialize.h:1166:44: note: in instantiation of function template specialization 'CSizeComputer::operator<<<CTransaction>' requested here
    return (CSizeComputer(nType, nVersion) << t).size();
                                           ^
miner.cpp:402:38: note: in instantiation of function template specialization 'GetSerializeSize<CTransaction>' requested here
            unsigned int nTxSize = ::GetSerializeSize(tx, SER_NETWORK, PROTOCOL_VERSION);
                                     ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/variant:1587:26: note: 'visit<SproutProofSerializer<OverrideStream<CSizeComputer> > &, const std::__1::variant<libzcash::PHGRProof, std::__1::array<unsigned char, 192> > &>' has been explicitly marked unavailable here
constexpr decltype(auto) visit(_Visitor&& __visitor, _Vs&&... __vs) {
                         ^
```

2020-12-09 14:57 UTC, nuttycom approved these changes
utACK

2020-12-09 15:10 UTC, nuttycom requested changes
Oops. Confirmed that this breaks the build on OSX.

2020-12-09 15:11 UTC, nuttycom commented
The error I get is "`value` is unavailable: introduced in macOS 10.14" - seems like it's not using the pinned clang? That'd be consistent with other complaints we've seen.

2020-12-10 01:32 UTC, daira approved these changes
utACK modulo macOS build issues.

2020-12-16 18:00 UTC, rex4539 approved these changes
ACK https://github.com/zcash/zcash/pull/4892/commits/77816bb8a02a7fe225f2ea40c489564370f06675

2020-12-16 18:57 UTC, nuttycom approved these changes
OSX build now works.

2020-12-16 23:05 UTC, str4d commented
Rebased to fix merge conflicts (in `src/miner.h` and `src/miner.cpp`, where scripted diffs changed lines adjacent to or moved by #4886). The only other change I needed to make was also as expected (https://github.com/zcash/zcash/pull/4886#discussion_r539242923) in the `Finish migrating to std::variant` commit.

2020-12-16 23:08 UTC, str4d commented
@zkbot r+

2020-12-17 00:02 UTC, daira approved these changes
ACK for the last two commits. I tested a native build on a macOS 10.13 (High Sierra) VM and zcashd still builds and works; I don't really know why it does, but it's convenient that I can still debug on macOS.

test_bitcoin fails to compile; I'll see if I can work around that in a separate PR.

2020-12-17 00:21 UTC, str4d commented
Transient failure, but I'll take this opportunity to apply the patch that @daira made to fix the High Sierra issue.

2020-12-17 00:45 UTC, str4d commented
@zkbot r+

2020-12-17 00:48 UTC, daira commented
Tested-on-macOS ACK for a8bcd46b8cdd7dfa4fc908dddd3d9bc968f32ad8.

2020-12-17 04:02 UTC, merged