Switch to ed25519-zebra for consensus signature checks
zcash/zcash pull request #4893
Opened 2020-12-04 03:50 UTC by str4d

ed25519-zebra can validate all signatures pre-Canopy, and now that Canopy
is active on mainnet, we don't need to worry about consensus divergence.

2020-12-04 03:54 UTC, str4d commented
This completes the changes made in efb4246ad3e90420438fc1066a1577b25d769c04.

2020-12-07 22:57 UTC, rex4539 requested changes
```
CXX      gtest/zcash_gtest-test_consensus.o
gtest/test_consensus.cpp:24:9: error: use of undeclared identifier 'librustzcash_zebra_crypto_sign_verify_detached'
        librustzcash_zebra_crypto_sign_verify_detached(
        ^
gtest/test_consensus.cpp:23:5: error: no type named 'Compare' in the global namespace
    EXPECT_EQ(
    ^~~~~~~~~~
/Users/rex/rex4539-zcash-ed25519-zebra-consensus/depends/x86_64-apple-darwin20.2.0/share/../include/gtest/gtest.h:1968:63: note: expanded from macro 'EXPECT_EQ'
                      EqHelper<GTEST_IS_NULL_LITERAL_(val1)>::Compare, \
                                                            ~~^
/Users/rex/rex4539-zcash-ed25519-zebra-consensus/depends/x86_64-apple-darwin20.2.0/share/../include/gtest/gtest_pred_impl.h:161:23: note: expanded from macro 'EXPECT_PRED_FORMAT2'
  GTEST_PRED_FORMAT2_(pred_format, v1, v2, GTEST_NONFATAL_FAILURE_)
                      ^~~~~~~~~~~
/Users/rex/rex4539-zcash-ed25519-zebra-consensus/depends/x86_64-apple-darwin20.2.0/share/../include/gtest/gtest_pred_impl.h:146:17: note: expanded from macro 'GTEST_PRED_FORMAT2_'
  GTEST_ASSERT_(pred_format(#v1, #v2, v1, v2), \
                ^~~~~~~~~~~
/Users/rex/rex4539-zcash-ed25519-zebra-consensus/depends/x86_64-apple-darwin20.2.0/share/../include/gtest/gtest_pred_impl.h:76:52: note: expanded from macro 'GTEST_ASSERT_'
  if (const ::testing::AssertionResult gtest_ar = (expression)) \
                                                   ^~~~~~~~~~
gtest/test_consensus.cpp:23:5: error: expected ')'
/Users/rex/rex4539-zcash-ed25519-zebra-consensus/depends/x86_64-apple-darwin20.2.0/share/../include/gtest/gtest.h:1967:3: note: expanded from macro 'EXPECT_EQ'
  EXPECT_PRED_FORMAT2(::testing::internal:: \
  ^
/Users/rex/rex4539-zcash-ed25519-zebra-consensus/depends/x86_64-apple-darwin20.2.0/share/../include/gtest/gtest_pred_impl.h:161:3: note: expanded from macro 'EXPECT_PRED_FORMAT2'
  GTEST_PRED_FORMAT2_(pred_format, v1, v2, GTEST_NONFATAL_FAILURE_)
  ^
/Users/rex/rex4539-zcash-ed25519-zebra-consensus/depends/x86_64-apple-darwin20.2.0/share/../include/gtest/gtest_pred_impl.h:146:29: note: expanded from macro 'GTEST_PRED_FORMAT2_'
  GTEST_ASSERT_(pred_format(#v1, #v2, v1, v2), \
                            ^
<scratch space>:12:1: note: expanded from here
"librustzcash_zebra_crypto_sign_verify_detached( sig.data(), (const unsigned char*)msg.data(), msg.size(), pubkey.data())"
^
gtest/test_consensus.cpp:23:5: note: to match this '('
/Users/rex/rex4539-zcash-ed25519-zebra-consensus/depends/x86_64-apple-darwin20.2.0/share/../include/gtest/gtest.h:1967:3: note: expanded from macro 'EXPECT_EQ'
  EXPECT_PRED_FORMAT2(::testing::internal:: \
  ^
/Users/rex/rex4539-zcash-ed25519-zebra-consensus/depends/x86_64-apple-darwin20.2.0/share/../include/gtest/gtest_pred_impl.h:161:3: note: expanded from macro 'EXPECT_PRED_FORMAT2'
  GTEST_PRED_FORMAT2_(pred_format, v1, v2, GTEST_NONFATAL_FAILURE_)
  ^
/Users/rex/rex4539-zcash-ed25519-zebra-consensus/depends/x86_64-apple-darwin20.2.0/share/../include/gtest/gtest_pred_impl.h:146:28: note: expanded from macro 'GTEST_PRED_FORMAT2_'
  GTEST_ASSERT_(pred_format(#v1, #v2, v1, v2), \
                           ^
gtest/test_consensus.cpp:62:9: error: use of undeclared identifier 'librustzcash_zebra_crypto_sign_verify_detached'
        librustzcash_zebra_crypto_sign_verify_detached(
        ^
gtest/test_consensus.cpp:61:5: error: no type named 'Compare' in the global namespace
    EXPECT_EQ(
    ^~~~~~~~~~
/Users/rex/rex4539-zcash-ed25519-zebra-consensus/depends/x86_64-apple-darwin20.2.0/share/../include/gtest/gtest.h:1968:63: note: expanded from macro 'EXPECT_EQ'
                      EqHelper<GTEST_IS_NULL_LITERAL_(val1)>::Compare, \
                                                            ~~^
/Users/rex/rex4539-zcash-ed25519-zebra-consensus/depends/x86_64-apple-darwin20.2.0/share/../include/gtest/gtest_pred_impl.h:161:23: note: expanded from macro 'EXPECT_PRED_FORMAT2'
  GTEST_PRED_FORMAT2_(pred_format, v1, v2, GTEST_NONFATAL_FAILURE_)
                      ^~~~~~~~~~~
/Users/rex/rex4539-zcash-ed25519-zebra-consensus/depends/x86_64-apple-darwin20.2.0/share/../include/gtest/gtest_pred_impl.h:146:17: note: expanded from macro 'GTEST_PRED_FORMAT2_'
  GTEST_ASSERT_(pred_format(#v1, #v2, v1, v2), \
                ^~~~~~~~~~~
/Users/rex/rex4539-zcash-ed25519-zebra-consensus/depends/x86_64-apple-darwin20.2.0/share/../include/gtest/gtest_pred_impl.h:76:52: note: expanded from macro 'GTEST_ASSERT_'
  if (const ::testing::AssertionResult gtest_ar = (expression)) \
                                                   ^~~~~~~~~~
gtest/test_consensus.cpp:61:5: error: expected ')'
/Users/rex/rex4539-zcash-ed25519-zebra-consensus/depends/x86_64-apple-darwin20.2.0/share/../include/gtest/gtest.h:1967:3: note: expanded from macro 'EXPECT_EQ'
  EXPECT_PRED_FORMAT2(::testing::internal:: \
  ^
/Users/rex/rex4539-zcash-ed25519-zebra-consensus/depends/x86_64-apple-darwin20.2.0/share/../include/gtest/gtest_pred_impl.h:161:3: note: expanded from macro 'EXPECT_PRED_FORMAT2'
  GTEST_PRED_FORMAT2_(pred_format, v1, v2, GTEST_NONFATAL_FAILURE_)
  ^
/Users/rex/rex4539-zcash-ed25519-zebra-consensus/depends/x86_64-apple-darwin20.2.0/share/../include/gtest/gtest_pred_impl.h:146:29: note: expanded from macro 'GTEST_PRED_FORMAT2_'
  GTEST_ASSERT_(pred_format(#v1, #v2, v1, v2), \
                            ^
<scratch space>:20:1: note: expanded from here
"librustzcash_zebra_crypto_sign_verify_detached( sig_hex.data(), (const unsigned char*)msg.data(), msg.size(), pubkey_hex.data())"
^
gtest/test_consensus.cpp:61:5: note: to match this '('
/Users/rex/rex4539-zcash-ed25519-zebra-consensus/depends/x86_64-apple-darwin20.2.0/share/../include/gtest/gtest.h:1967:3: note: expanded from macro 'EXPECT_EQ'
  EXPECT_PRED_FORMAT2(::testing::internal:: \
  ^
/Users/rex/rex4539-zcash-ed25519-zebra-consensus/depends/x86_64-apple-darwin20.2.0/share/../include/gtest/gtest_pred_impl.h:161:3: note: expanded from macro 'EXPECT_PRED_FORMAT2'
  GTEST_PRED_FORMAT2_(pred_format, v1, v2, GTEST_NONFATAL_FAILURE_)
  ^
/Users/rex/rex4539-zcash-ed25519-zebra-consensus/depends/x86_64-apple-darwin20.2.0/share/../include/gtest/gtest_pred_impl.h:146:28: note: expanded from macro 'GTEST_PRED_FORMAT2_'
  GTEST_ASSERT_(pred_format(#v1, #v2, v1, v2), \
                           ^
6 errors generated.
make[2]: *** [gtest/zcash_gtest-test_consensus.o] Error 1
```

2020-12-08 14:29 UTC, daira approved these changes
utACK modulo the macOS build issue. Needs three reviews and a test that reindex/sync still works correctly.

2020-12-08 15:00 UTC, rex4539 approved these changes
ACK https://github.com/zcash/zcash/pull/4893/commits/4ca2b20496952ebc7292e19eeaf42cda52896926

2020-12-08 16:52 UTC, rex4539 commented
Many RPC tests fail.

2020-12-08 17:05 UTC, rex4539 requested changes
```
Running stage rpc
=================

......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
mergetoaddress_sapling.py:
Pass: True, Duration: 517 s

................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
mergetoaddress_sprout.py:
Pass: True, Duration: 747 s

...................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
wallet_shieldingcoinbase.py:
Pass: True, Duration: 1207 s

.............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
remove_sprout_shielding.py:
Pass: True, Duration: 328 s

..........................................................................................................................................................................................................................................................................................................................................................................................................................
sprout_sapling_migration.py:
Pass: True, Duration: 534 s

.........................................................................................................................................................................................................................................................................................................................
wallet_shieldcoinbase_sprout.py:
Pass: True, Duration: 691 s

.........................
zcjoinsplitdoublespend.py:
Pass: True, Duration: 376 s

.............................................................................................................................................................................................................................
mergetoaddress_mixednotes.py:
Pass: True, Duration: 124 s

.............................................................................................................................................................................................................................................................
turnstile.py:
Pass: True, Duration: 127 s

..............................................................................................................................................................................................
zcjoinsplit.py:
Pass: True, Duration: 505 s

........................................................................................................................................................................................
wallet_shieldcoinbase_sapling.py:
Pass: True, Duration: 428 s

...............................................................................
zkey_import_export.py:
Pass: True, Duration: 133 s

................................. [...]

2020-12-08 20:06 UTC, str4d commented
Those seem like unrelated test failures, likely related to the migration to `rpc-tests.py`. But let's fire off a CI run to check:

@zkbot try

2020-12-08 20:40 UTC, rex4539 commented
I will file a separate bug.

2020-12-08 21:08 UTC, rex4539 approved these changes

2020-12-09 13:03 UTC, str4d commented
I've updated the minimum chain work, and pinned all NU activation block hashes up to Canopy, since after this change our node relies on Canopy being active on the main chain.

2020-12-11 15:10 UTC, daira approved these changes
utACK ceccb10e4f1353593b3e1f0e668853a7657d63f6

2020-12-11 15:11 UTC, daira commented
Merge policy for consensus changes is three reviews, at least two from ECC engineers. @zkbot r+

2020-12-11 16:03 UTC, merged