Hide password in -stdin `walletpassphrase`
zcash/zcash pull request #4936
Opened 2020-12-30 15:14 UTC by oxarbitrage

An approach for issue https://github.com/zcash/zcash/issues/4932

Code in this PR will hide the first line of input when we are in `-stdin` mode and only when the `walletpassphrase` command is used. This works for me but i understand it can be confusing, open to other options.

Without this PR:

```
$ ./src/zcash-cli -stdin walletpassphrase\n
mypass\n
120\n
<Ctrl+D>
$
```

With PR:

```
$ ./src/zcash-cli -stdin walletpassphrase\n
[here we type the password and enter but this is not shown]
120\n
<Ctrl+D>
$
```

Function `SetStdinEcho` is not mine(https://stackoverflow.com/a/1455007). It works in linux, it should work in windows, not sure about mac.

This PR also moves the `-stdin` option to the Options section of the cli help.

------------
Please ensure this checklist is followed for any pull requests for this repo. This checklist must be checked by both the PR creator and by anyone who reviews the PR.
* [ ] Relevant documentation for this PR has to be completed and reviewed by @mdr0id before the PR can be merged
* [ ] A test plan for the PR must be documented in the PR notes and included in the test plan for the next regular release

As a note, all buildbot tests need to be passing and all appropriate code reviews need to be done before this PR can be merged

2021-01-01 12:49 UTC, daira commented on src/bitcoin-cli.cpp
> +            if (strncmp(argv[1], "walletpassphrase", 16) == 0) {
```suggestion
            if (argc > 1 && args[0] == "walletpassphrase") {
```

2021-01-01 12:58 UTC, daira requested changes
Change needed.

2021-01-01 13:01 UTC, daira commented on src/bitcoin-cli.cpp
> +    HANDLE hStdin = GetStdHandle(STD_INPUT_HANDLE);
```suggestion
    HANDLE hStdin = GetStdHandle(STD_INPUT_HANDLE);
    assert(hStdin != INVALID_HANDLE_VALUE && hStdin != NULL);
```

2021-01-01 13:02 UTC, daira commented on src/bitcoin-cli.cpp
> +    GetConsoleMode(hStdin, &mode);
```suggestion
    assert(GetConsoleMode(hStdin, &mode) != 0);
```

2021-01-01 13:04 UTC, daira commented on src/bitcoin-cli.cpp
> +void SetStdinEcho(bool enable = true)
```suggestion
bool SetStdinEcho(bool enable = true)
```

2021-01-01 13:06 UTC, daira commented on src/bitcoin-cli.cpp
> +    SetConsoleMode(hStdin, mode);
```suggestion
    if (SetConsoleMode(hStdin, mode) == 0) return false;
```

2021-01-01 13:21 UTC, daira commented on src/bitcoin-cli.cpp
> +    tcgetattr(STDIN_FILENO, &tty);
```suggestion
    if (tcgetattr(STDIN_FILENO, &tty) != 0) return false;
```

2021-01-01 13:22 UTC, daira commented on src/bitcoin-cli.cpp
> +    (void) tcsetattr(STDIN_FILENO, TCSANOW, &tty);
```suggestion
    if (tcsetattr(STDIN_FILENO, TCSANOW, &tty) != 0) return false;
```

2021-01-01 13:22 UTC, daira commented on src/bitcoin-cli.cpp
> +#endif
```suggestion
#endif
    return true;
```

2021-01-01 13:25 UTC, daira commented on src/bitcoin-cli.cpp
> +                    SetStdinEcho(true);
```suggestion
                    if (!SetStdinEcho(true))
                        throw std::runtime_error("unable to set terminal back to echoing");
```

2021-01-01 13:25 UTC, daira commented on src/bitcoin-cli.cpp
> +                SetStdinEcho(false);
```suggestion
                if (!SetStdinEcho(false))
                    throw std::runtime_error("unable to set terminal to non-echoing");
```

2021-01-01 13:33 UTC, daira commented on src/bitcoin-cli.cpp
> +#include <unistd.h>
```suggestion
#include <unistd.h>
#include <cerrno>
```

2021-01-02 14:13 UTC, daira approved these changes
utACK. Needs one more review (especially of the code added by my suggestions), and testing on Windows, Linux, and macOS. The testing should also cover the case where input is redirected.

2021-01-04 15:07 UTC, daira commented
Tested on Windows 8.1, in both `cmd.exe` and Powershell:
* `.\zcash-cli --stdin walletpassphrase` does not echo the first line of input, but does echo the rest.
* `type foo.txt |.\zcash-cli --stdin walletpassphrase` does not complain and takes the first line of `foo.txt` as the passphrase.
* other RPC commands are not affected.

2021-01-04 15:38 UTC, daira commented
Also tested on Linux.

2021-01-12 15:35 UTC, nuttycom commented
Works fine on OSX.

2021-01-14 14:13 UTC, nuttycom approved these changes
ACK

2021-01-14 14:13 UTC, nuttycom commented
@zkbot r+

2021-01-14 17:49 UTC, merged