Backport bitcoin/bitcoin#8173 (Use SipHash for node eviction)
zcash/zcash pull request #4985
Opened 2021-02-15 23:17 UTC by nuttycom

Backport of bitcoin/bitcoin#8173

    - pick bitcoin/bitcoin@eebc232187
    - pick bitcoin/bitcoin@888483098e
    - pick bitcoin/bitcoin@c31b24f745
    - pick bitcoin/bitcoin@9bf156bb9e
    - pick bitcoin/bitcoin@053930ffc4
       - missing bitcoin/bitcoin#5697 (not a candidate for direct inclusion), using pieces directly
       - conflicts with zcash/zcash#1258 which it removes part of (this is ok)
          - ignore bitcoin/bitcoin#6374
          - requires bitcoin/bitcoin#7906, or at least bitcoin/bitcoin@cca221fd21
             - pick bitcoin/bitcoin@cca221fd21
       - conflicts with bitcoin/bitcoin#7181, not needed until later if at all

2021-02-15 23:18 UTC, nuttycom commented
Subsumes #4980

2021-02-16 12:51 UTC, str4d requested changes
Two fixes, otherwise utACK 7d71a2384346d71389f0da3d11e12089e4785a3e.

2021-02-16 12:51 UTC, str4d commented on src/net.cpp
> +    BOOST_FOREACH(const NodeEvictionCandidate &node, vEvictionCandidates) {
Take care to not revert these kinds of cleanups when cherry-picking (the original commit was prior to `BOOST_FOREACH` removal). Squash this revert into 0a369a5091b799332ed6e26e53d05dd8181e1ec1 (so it lines up more closely with the original commit):
```suggestion
    for (const NodeEvictionCandidate &node, vEvictionCandidates) {
```

2021-02-16 12:51 UTC, str4d commented on src/net.cpp
> +                .nVersion = node->nVersion,
This doesn't compile. Squash this fix into 74bfd9a5c39e9fcd54416e3748f62f483f9b05b9:
```suggestion
                .vchKeyedNetGroup = node->vchKeyedNetGroup,
                .nVersion = node->nVersion
```

2021-02-17 03:15 UTC, str4d commented on src/net.cpp
> +    BOOST_FOREACH(const NodeEvictionCandidate &node, vEvictionCandidates) {
This is not yet resolved.

2021-02-17 16:38 UTC, str4d approved these changes
utACK.

2021-02-17 16:39 UTC, str4d commented
@zkbot r+

2021-02-17 17:33 UTC, merged