add missing aarch64 build deps
zcash/zcash pull request #5289
Opened 2021-09-04 23:29 UTC by hexabot

#4930

fix missing build dependencies for aarch64

2021-09-05 07:54 UTC, daira submitted a review, later dismissed
utACK. Someone should independently test this on Aarch64 Linux before we merge.

2021-09-06 15:57 UTC, str4d requested changes

2021-09-06 15:57 UTC, str4d commented on depends/packages/native_clang.mk
> +$(package)_sha256_hash_aarch64_linux=39b3d3e3b534e327d90c77045058e5fc924b1a81d349eac2be6fb80f4a0e40d4
This hash is out-of-date. It is the hash for Clang 11.0.1, but we updated to 12.0.1 in #5262. This should be:
```suggestion
$(package)_sha256_hash_aarch64_linux=3d4ad804b7c85007686548cbc917ab067bf17eaedeab43d9eb83d3a683d8e9d4
```

2021-09-06 15:57 UTC, str4d commented on depends/packages/native_rust.mk
> +$(package)_sha256_hash_aarch64_linux=fd31c78fffad52c03cac5a7c1ee5db3f34b2a77d7bc862707c0f71e209180a84
This hash is wrong. I took a guess, and figured out it is the hash for 1.51.0, but we updated to 1.54.0 in #5262. This should be:
```suggestion
$(package)_sha256_hash_aarch64_linux=33a50c5366a57aaab43c1c19e4a49ab7d8ffcd99a72925c315fb1f9389139e6f
```

2021-09-08 11:42 UTC, daira approved these changes
utACK, but I still have not tested this on AArch64.

2021-09-08 17:47 UTC, str4d approved these changes
Tested ACK. I was able to build `zcashd` on an aarch64 machine.

2021-09-08 17:47 UTC, merged