Smoke Test Updates (Remove Sprout Logic )
zcash/zcash pull request #5293
Opened 2021-09-09 22:00 UTC by mdr0id

Closes and cleans up https://github.com/zcash/zcash/pull/5239

2021-09-10 11:29 UTC, daira approved these changes
utACK

2021-09-10 12:11 UTC, str4d requested changes

2021-09-10 12:11 UTC, str4d commented on qa/zcash/smoke_tests.py
> +        taddr_balance = sapling_balance - (Decimal('2') * DEFAULT_FEE)
```suggestion
        taddr_balance += sapling_balance - (Decimal('2') * DEFAULT_FEE)
```

2021-09-10 12:11 UTC, str4d commented on qa/zcash/smoke_tests.py
>          taddr_balance = Decimal('0')
```suggestion
        taddr_balance -= taddr_2_balance
```

2021-09-11 02:52 UTC, mdr0id commented
@str4d Updated comments and added brief usage doc

2021-09-11 09:02 UTC, daira submitted a review, later dismissed
re-utACK b6987844f8ed7d39b3f09d6b4a913f9ce76bda0c

2021-09-11 14:16 UTC, str4d requested changes
I double-checked the math around the PR changes.

2021-09-11 14:16 UTC, str4d commented on qa/zcash/smoke_tests.py
>          taddr_balance += (starting_balance / Decimal('10')) * Decimal('4')
```suggestion
        taddr_balance += (starting_balance / Decimal('10')) * Decimal('2')
```

2021-09-11 14:16 UTC, str4d commented on qa/zcash/smoke_tests.py
>          taddr_balance -= (starting_balance / Decimal('10')) * Decimal('4')
```suggestion
        taddr_balance -= (starting_balance / Decimal('10')) * Decimal('2')
```

2021-09-11 14:16 UTC, str4d commented on qa/zcash/smoke_tests.py
> +        taddr_balance += sapling_balance - (2 * DEFAULT_FEE)
```suggestion
        taddr_balance += sapling_balance - DEFAULT_FEE
```

2021-09-11 14:16 UTC, str4d commented on qa/zcash/smoke_tests.py
> +        taddr_balance += sapling_balance - (Decimal('2') * DEFAULT_FEE)
```suggestion
        taddr_balance += sapling_balance - DEFAULT_FEE
```

2021-09-15 00:46 UTC, str4d approved these changes
utACK

2021-09-15 08:38 UTC, merged