test: automatically add missing nuparams (network upgrade heights)
zcash/zcash pull request #5403
Opened 2021-12-03 20:51 UTC by LarryRuane

This test-only change simplifies python (rpc) tests by allowing them to specify, for example, that NU5 should be activated at height X, without having to specify all the previous network upgrades. Previous upgrades can (and must) still be specified if the test needs them to activate at different block heights (than, in this example, NU5). This makes tests easier to write (and read), especially as the number of network upgrades increases over time.

Note that this change only affects zcashd behavior in regtest mode. For the other network modes (testnet and mainnet), the activation heights are hard-coded in chainparams.cpp.

2021-12-06 21:21 UTC, str4d requested changes
I'm looking forward to this!

2021-12-06 21:21 UTC, str4d commented on src/init.cpp
> +        //    nuparams(NU5_BRANCH_ID, 210),
Add an RPC test that confirms setting `nuparams` for Heartwood and NU5 only, results in `getblockchaininfo` reporting that:
- Sprout, Overwinter, and Sapling are active from height 1 (due to test framework defaults).
- Blossom is active from the same height as Heartwood.
- Canopy is active from the same height as NU5.

2021-12-07 00:30 UTC, LarryRuane commented
Thanks for the review, @str4d, force-pushed a new Python test.

2021-12-07 00:33 UTC, LarryRuane commented
(one more force-push for linter)

2021-12-17 00:41 UTC, str4d approved these changes
utACK. Nice!

2021-12-17 00:42 UTC, merged