Avoid a warning by explicitly calling drop
zcash/zcash pull request #5459
Opened 2022-01-10 00:00 UTC by daira

This fixes the following spurious warning:
```
   Compiling librustzcash v0.2.0 (/home/daira/zecc/zcash)
warning: unused return value of `CString::from_raw` that must be used
  --> src/rust/src/zip339_ffi.rs:66:13
   |
66 |             CString::from_raw(phrase as *mut c_char);
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_must_use)]` on by default
   = note: call `drop(from_raw(ptr))` if you intend to drop the `CString`
```

Signed-off-by: Daira Hopwood <daira@jacaranda.org>

2022-01-10 00:13 UTC, nuttycom approved these changes
ACK

2022-01-10 01:19 UTC, nuttycom requested changes
Oh, hey, I just noticed that on the feature/wallet_unified addresses branch the implementation is now this:
```
            CString::from_raw(phrase as *mut c_char)
                .into_bytes()
                .zeroize();
```

IIRC @str4d requested that the memory be zeroed before being dropped.

2022-01-10 02:42 UTC, nuttycom approved these changes
ACK

2022-01-11 02:46 UTC, merged

2022-01-11 12:31 UTC, daira commented
Oops, the PR title (that goes into the merge commit) was inaccurate: we don't need to explicitly call `drop` to avoid the warning, given the zeroization. I'll try to remember to check PR titles in future.

2022-01-11 13:34 UTC, str4d commented
I would have preferred that we simply didn't merge this at all, since we'd fixed it in the UA wallet integration branch.