z_listreceivedbyaddress: reject UA component addr (#5537)
zcash/zcash pull request #5545
Opened 2022-02-14 20:48 UTC by LarryRuane

Closes #5537

2022-02-15 14:56 UTC, str4d commented on src/wallet/rpcwallet.cpp
> +            return false;
```suggestion
            // We allow unified addresses themselves.
            return false;
```

2022-02-15 14:56 UTC, nuttycom requested changes
Looks good, one minor change is needed to how the error is reported.

2022-02-15 14:56 UTC, nuttycom commented on src/wallet/rpcwallet.cpp
> +        throw JSONRPCError(RPC_INVALID_PARAMETER, "z_listreceivedbyaddress does not allow a unified address argument");
```suggestion
        throw JSONRPCError(RPC_INVALID_PARAMETER, "The provided address is a bare receiver from a Unified Address in this wallet. Provide the full UA instead.");
```

2022-02-15 14:56 UTC, nuttycom commented on qa/rpc-tests/wallet_listreceived.py
> +            "z_listreceivedbyaddress does not allow a unified address argument",
```suggestion
            "The provided address is a bare receiver from a Unified Address in this wallet. Provide the full UA instead.",
            node.z_listreceivedbyaddress, receivers['transparent'], 0)
        assert_raises_message(
            JSONRPCException,
            "The provided address is a bare receiver from a Unified Address in this wallet. Provide the full UA instead.",
```

2022-02-15 20:07 UTC, nuttycom approved these changes
utACK

2022-02-16 16:30 UTC, str4d approved these changes

2022-02-16 16:30 UTC, merged

2022-02-16 22:33 UTC, daira commented on src/wallet/rpcwallet.cpp
> +    // unified address known to this wallet is not allowed.
Wait, why not? This seems like an odd exception. What if the provider of the bare address doesn't know the full UA? Why should an address that happens to be part of a UA known to the wallet behave differently to any other bare address? I would definitely have pushed back on this if I hadn't been distracted by unrelated stuff yesterday.