Recover orchard keys and mappings during wallet load
zcash/zcash pull request #5612
Opened 2022-03-01 17:22 UTC by ebfull

Closes #5567

Everything is already persisted, we just need to reconstruct the in-memory maps. The IVK -> FVK maps are already reloaded during wallet loading inside of `AddUnifiedFullViewingKey` (that map exists inside of the keystore itself rather than the wallet). This PR just reloads the Orchard spending keys and the addr -> IVK maps (inside the wallet) for Orchard addresses (both internal and per-address).

First commit just consolidates cache reconstruction for unified addresses into a single function.

2022-03-02 00:24 UTC, nuttycom approved these changes
utACK modulo test failures, which should be resolved by #5614

2022-03-02 23:00 UTC, daira commented on src/wallet/wallet.cpp
> +            // we cannot recover the secret keys.
Log this.

2022-03-02 23:01 UTC, daira commented on src/wallet/wallet.cpp
> +                    // address records loaded.
Log this also.

2022-03-02 23:01 UTC, daira commented on src/wallet/wallet.cpp
> +                    // Unable to generate a unified spending key for this account ID.
And log this.

2022-03-02 23:01 UTC, daira commented on src/wallet/wallet.cpp
> +                        // Unable to generate a default internal address
Log this.

2022-03-02 23:02 UTC, daira commented on src/wallet/wallet.cpp
> +                                    // Unable to add an orchard address -> IVK mapping to the wallet
Log this.

2022-03-02 23:02 UTC, daira commented on src/wallet/wallet.cpp
> +                                // metadata.
Log this.

2022-03-02 23:02 UTC, daira requested changes
Please add logging for error conditions.

2022-03-03 00:51 UTC, daira approved these changes
utACK

2022-03-03 14:42 UTC, str4d approved these changes
utACK bd137561f2fa19c42589b818a9f16a9146d874b2

2022-03-03 14:47 UTC, nuttycom approved these changes
utACK https://github.com/zcash/zcash/commit/bd137561f2fa19c42589b818a9f16a9146d874b2

2022-03-03 14:47 UTC, merged