[WIP] Report conflicted Orchard spends
zcash/zcash pull request #5649
Opened 2022-03-09 16:51 UTC by therealyingtong

Closes #5593. 

TODO: test this in `test_wallet.cpp`.

2022-03-10 15:17 UTC, daira reviewed
Needs a test.

2022-03-10 15:19 UTC, nuttycom requested changes

2022-03-10 15:19 UTC, nuttycom commented on src/wallet/wallet.cpp
> +    }
`mapTxOrchardNullifiers` is newly added and is not populated anywhere. Instead, get this information from the `potential_spends` field of the Orchard sub-wallet.

2022-03-12 02:10 UTC, nuttycom approved these changes
utACK

2022-03-12 02:16 UTC, str4d requested changes
Otherwise LGTM. If this PR is rebased or force-pushed, please squash the two commits together.

2022-03-12 02:16 UTC, str4d commented on src/wallet/wallet.cpp
> +        OrchardOutPoint op(i, wtx.GetHash());
These are backwards:
```suggestion
        OrchardOutPoint op(wtx.GetHash(), i);
```

2022-03-14 20:20 UTC, ebfull approved these changes

2022-03-14 23:46 UTC, merged

2022-03-15 12:43 UTC, daira commented
Post-hoc ACK given https://github.com/zcash/zcash/issues/5648#issuecomment-1064166571