Check that duplicate Orchard nullifiers within transactions are rejected
zcash/zcash pull request #5761
Opened 2022-03-28 19:40 UTC by ebfull

2022-03-28 19:59 UTC, nuttycom requested changes

2022-03-28 19:59 UTC, nuttycom commented on src/gtest/test_transaction_builder.cpp
> +    RegtestDeactivateNU5();
Why does this deactivate without a corresponding activation?

2022-03-28 21:51 UTC, ebfull commented
FYI here are the changes to the `orchard` crate I made for this PR locally.

```
diff --git a/src/builder.rs b/src/builder.rs
index 4a207c2..721d39a 100644
--- a/src/builder.rs
+++ b/src/builder.rs
@@ -51,7 +51,7 @@ impl From<value::OverflowError> for Error {
 }
 
 /// Information about a specific note to be spent in an [`Action`].
-#[derive(Debug)]
+#[derive(Debug, Clone)]
 struct SpendInfo {
     dummy_sk: Option<SpendingKey>,
     fvk: FullViewingKey,
@@ -224,6 +224,17 @@ impl Builder {
         }
     }
 
+    /// lol
+    pub fn add_duplicate_nullifier_spend(
+        &mut self,
+        mut rng: impl RngCore,
+    )
+    {
+        let spend = SpendInfo::dummy(&mut rng);
+        self.spends.push(spend.clone());
+        self.spends.push(spend);
+    }
+
     /// Adds a note to be spent in this transaction.
     ///
     /// Returns an error if the given Merkle path does not have the required anchor for
diff --git a/src/tree.rs b/src/tree.rs
index 874d08e..305e44f 100644
--- a/src/tree.rs
+++ b/src/tree.rs
@@ -75,7 +75,7 @@ impl Anchor {
 
 /// The Merkle path from a leaf of the note commitment tree
 /// to its anchor.
-#[derive(Debug)]
+#[derive(Debug, Clone)]
 pub struct MerklePath {
     position: u32,
     auth_path: [MerkleHashOrchard; MERKLE_DEPTH_ORCHARD],
```

2022-03-28 22:53 UTC, nuttycom approved these changes
utACK

2022-03-29 01:29 UTC, therealyingtong approved these changes
utACK

2022-03-29 03:27 UTC, nuttycom commented
CI failures are unrelated nondeterministic RPC test issues.

2022-03-29 03:27 UTC, merged

2022-03-29 04:14 UTC, str4d approved these changes
utACK. I didn't check the test in this PR passes, but I did update my `zcash-inspect` tool to check this consensus rule.

2022-03-29 04:14 UTC, str4d commented on src/gtest/data/tx-orchard-duplicate-nullifiers.h
> +const char *txdataOrchardDuplicateNullifiersTestVector = "050000800a27a726b4d0d6c20000000029000000013412000000000000000000000000000000000000000000000000000000000000000000006a4730440220635eb46b6e39e2e
I verified that this does indeed contain two Orchard actions that use the same nullifier (and a valid proof, indicating the actions double-spend the same note).

2022-03-29 11:40 UTC, daira reviewed
Post-hoc ACK