Add z_listaccounts API.
zcash/zcash pull request #5791
Opened 2022-04-01 08:49 UTC by therealyingtong

Closes #5635

2022-04-01 13:36 UTC, nuttycom requested changes

2022-04-01 13:36 UTC, nuttycom commented on src/wallet/rpcwallet.cpp
> +            address.pushKV("diversifier", j.ToString());
```suggestion
            UniValue jVal;
            jVal.setNumStr(ArbitraryIntStr(std::vector(j.begin(), j.end())));
            addrEntry.pushKV("diversifier_index", jVal);
```

2022-04-01 13:36 UTC, nuttycom commented on src/wallet/rpcwallet.cpp
> +    for (int acctId = 0; acctId < num_accounts; acctId++) {
Why iterate over the account counter rather than just iterate over `mapUnifiedAccountKeys` directly?

2022-04-06 13:27 UTC, nuttycom requested changes
It looks like the test needs to be completed; also a few small style suggestions.

2022-04-06 13:27 UTC, nuttycom commented on src/wallet/rpcwallet.cpp
> +    for (auto accountMap = accountsMap.begin(); accountMap != accountsMap.end(); accountMap++) {
```suggestion
    for (const auto& [acctKey, ufvkId] : pwalletMain->mapUnifiedAccountKeys) {
```

2022-04-06 13:27 UTC, nuttycom commented on src/wallet/rpcwallet.cpp
> +        auto ufvkId = accountMap->second;
```suggestion
```

2022-04-06 13:27 UTC, nuttycom commented on src/wallet/rpcwallet.cpp
> +        for (auto it = diversifiersMap.begin(); it != diversifiersMap.end(); it++) {
```suggestion
        for (const auto& [j, receiverTypes] : diversifiersMap) {
```

2022-04-06 13:27 UTC, nuttycom commented on src/wallet/rpcwallet.cpp
> +            auto j = it->first;
```suggestion
```

2022-04-06 13:27 UTC, nuttycom commented on src/wallet/rpcwallet.cpp
> +            auto uaPair = std::get<std::pair<UnifiedAddress, diversifier_index_t>>(ufvkInfo->Address(it->first, it->second));
```suggestion
            auto uaPair = std::get<std::pair<UnifiedAddress, diversifier_index_t>>(ufvk.Address(j, receiverTypes));
```

2022-04-06 13:27 UTC, nuttycom commented on src/wallet/rpcwallet.cpp
> +        auto ufvkInfo = pwalletMain->GetUnifiedFullViewingKey(ufvkId);
```suggestion
        auto ufvk = pwalletMain->GetUnifiedFullViewingKey(ufvkId).value();
```

2022-04-07 08:35 UTC, therealyingtong commented on qa/rpc-tests/wallet_z_listaccounts.py
> +        self.setup_clean_chain = True
I didn't mean to add this test actually -- I'll just inline it in some other test.

2022-04-08 13:59 UTC, nuttycom approved these changes
utACK

2022-04-08 15:11 UTC, daira commented on qa/rpc-tests/wallet_accounts.py
> +        assert_equal(accounts[0]['account'], 0)
This and the checks below should probably check the length of `accounts`, to make sure there are no spurious ones.

2022-04-08 15:14 UTC, daira commented on src/wallet/rpcwallet.cpp
> +            "        {\n"
This isn't valid JSON syntax, I think it should be something like `"addresses": [{...}, ...]`.

2022-04-08 15:14 UTC, daira requested changes
The error in the help text is blocking.

2022-04-08 19:31 UTC, daira approved these changes
utACK

2022-04-08 21:30 UTC, merged