Make Orchard `finalState` serialization format match Sapling.
zcash/zcash pull request #5852
Opened 2022-04-08 18:57 UTC by nuttycom

For consistency, we serialize the `finalState` field in the
same (sparse) encoding as Sapling and Sprout use. In the future
we may want to update this to the dense encoding that
incrementalmerkletree::bridgetree::Frontier uses, but that's not
necessary for the moment.

Please ensure this checklist is followed for any pull requests for this repo. This checklist must be checked by both the PR creator and by anyone who reviews the PR.
* [ ] Relevant documentation for this PR has to be completed and reviewed by @mdr0id before the PR can be merged
* [ ] A test plan for the PR must be documented in the PR notes and included in the test plan for the next regular release

As a note, all buildbot tests need to be passing and all appropriate code reviews need to be done before this PR can be merged

2022-04-08 22:20 UTC, daira approved these changes
utACK

2022-04-09 00:09 UTC, str4d requested changes
utACK once comment addressed.

2022-04-09 00:41 UTC, str4d approved these changes
utACK 176b77ea0395a7be429e1eb3a1f49c35d2213ed9

2022-04-09 01:42 UTC, str4d requested changes
`finalsaplingroot` RPC test needs to be updated to check the sparse format.

2022-04-09 03:07 UTC, nuttycom commented
Tests fixed; failed checks are now node evictions.

2022-04-09 03:07 UTC, merged