Backport sanity checks that verify that std::chrono::time agrees with time()
zcash/zcash pull request #6051
Opened 2022-07-05 18:42 UTC by nuttycom

Backport of the first commit of bitcoin/bitcoin#21110 and of bitcoin/bitcoin#18358

2022-07-05 18:42 UTC, nuttycom commented
This builds upon #6043

2022-07-06 20:37 UTC, daira submitted a review, later dismissed
utACK

2022-07-07 16:02 UTC, str4d requested changes
Backports LGTM. Commit message needs to be altered as below, and also please add `bitcoin/bitcoin@` prefix to the `cherry picked from commit X` lines (i.e. change them to `cherry picked from commit bitcoin/bitcoin@X`) so that GitHub links them correctly.

2022-07-07 16:02 UTC, str4d commented on src/util/time.cpp
>  #endif
The upstream commit being backported was merged before `ChronoSanityCheck` was added, so why was this change not made upstream then?

Please add a `Zcash: Some description` message to the commit message that notes what the changes are relative to the upstream commit and why (so they are preserved in git history).

2022-07-08 14:18 UTC, closed without merging