Fix orchard anchor hash serialization
zcash/zcash pull request #6152
Opened 2022-09-09 17:55 UTC by sellout

In the RPC response, orchard anchors were serialized differently from the final orchard root they referred to, making it difficult to correlate the two. This changes them to match.

Please ensure this checklist is followed for any pull requests for this repo. This checklist must be checked by both the PR creator and by anyone who reviews the PR.
* [ ] Relevant documentation for this PR has to be completed and reviewed by @mdr0id before the PR can be merged
* [ ] A test plan for the PR must be documented in the PR notes and included in the test plan for the next regular release

As a note, all buildbot tests need to be passing and all appropriate code reviews need to be done before this PR can be merged

2022-09-15 00:32 UTC, daira requested changes
This is an incompatible change. If we decide to do it, then the change would need to be documented in the release notes and RPC help.

2022-09-15 00:36 UTC, nuttycom reviewed
I agree with @daira - I think we should do this, but it needs to be mentioned in the release notes. Update `doc/release_notes.md` to describe this change so that it will be automatically included the next time we cut a release.

2022-09-15 17:28 UTC, sellout commented
This has been force pushed, folding #6158 into this change, and updating the release_notes and RPC docs.

2022-09-15 18:01 UTC, nuttycom approved these changes
utACK with minor documentation suggestions.

2022-09-15 18:49 UTC, nuttycom commented on src/rpc/blockchain.cpp
> +            "                              output in prior releases up to v5.2.0. This has now been rectified.\n"```
```suggestion
            "                              output in prior releases up to v5.2.0. This has now been rectified.\n"
```

2022-09-23 13:56 UTC, nuttycom submitted a review, later dismissed
utACK

2022-09-23 23:47 UTC, daira commented on qa/rpc-tests/finalorchardroot.py
> +        pass
```suggestion
```

2022-09-23 23:49 UTC, str4d approved these changes
utACK bdde47fb5d6d8dfbdbbc93c4e1168101ee65cbc2

2022-09-23 23:49 UTC, daira commented on src/rpc/blockchain.cpp
> +            "                                   output in prior releases up to v5.2.0. This has now been rectified.\n"
```suggestion
            "                                   output in prior releases up to and including v5.2.0. This has now been\n"
            "                                   rectified.\n"
```
("up to" is ambiguous.)

2022-09-23 23:50 UTC, daira commented on src/rpc/blockchain.cpp
> +            "                              output in prior releases up to v5.2.0. This has now been rectified.\n"
```suggestion
            "                              output in prior releases up to v5.2.0. This has now been\n"
            "                              rectified.\n"
```

2022-09-23 23:51 UTC, daira approved these changes
utACK with minor suggestions.

2022-09-24 01:33 UTC, nuttycom approved these changes
utACK https://github.com/zcash/zcash/pull/6152/commits/5514542a0a8e1ad62637fd4d502bfd1cce1ae69a

2022-09-24 01:53 UTC, merged

2022-09-24 02:45 UTC, daira reviewed
Post-hoc ACK 5514542a0a8e1ad62637fd4d502bfd1cce1ae69a