Remove outdated Sprout tests
zcash/zcash pull request #6316
Opened 2023-01-03 22:28 UTC by sellout

These tests included operations that are no longer supported. Future changes will break them, so the tests have either been removed or updated as appropriate.

2023-01-10 15:53 UTC, nuttycom approved these changes
utACK

2023-01-10 15:53 UTC, nuttycom commented on qa/rpc-tests/wallet_listnotes.py
> -        assert_equal(False,             unspent_tx[0]['change'])
These reorderings seem trivial; did I do those? If so I don't think there was a good reason, and they should probably be reverted.

2023-01-10 15:55 UTC, nuttycom requested changes
Looks like a number of tests are failing now that deprecated methods have been disabled?

2023-01-10 23:04 UTC, nuttycom approved these changes
utACK https://github.com/zcash/zcash/pull/6316/commits/86c019fdfb4480415586a6fd04a6514c721843f2

2023-01-11 20:47 UTC, str4d approved these changes
utACK

2023-01-11 20:47 UTC, merged