Fix a couple of longstanding zcashd build warnings
zcash/zcash pull request #6476
Opened 2023-03-11 16:11 UTC by nuttycom

Fixes zcash/zcash#2348

2023-03-11 18:01 UTC, str4d requested changes
Backport request, and 3 questions.

2023-03-11 18:01 UTC, str4d commented on Makefile.am
> -GZIP_ENV="-9n"
This was removed upstream in https://github.com/bitcoin/bitcoin/pull/11541, which was similarly fixing automake warnings. We should just backport the first commit from that PR (as it also removes some other code we similarly don't need).

2023-03-12 01:09 UTC, nuttycom commented on src/secp256k1/configure.ac
> +AC_PROG_CC
The build was reporting that `AC_PROG_CC_C99` is obsolete and recommended running `autoupdate`. That is also what introduced the `2.71` bump.

2023-03-13 14:47 UTC, nuttycom commented on src/secp256k1/configure.ac
> +AC_PROG_CC
Reverted.

2023-03-13 15:28 UTC, str4d submitted a review, later dismissed
utACK fc0621bfae34d43d310f6f347473e748a2979e57

2023-03-13 15:59 UTC, daira approved these changes
utACK

2023-03-13 17:51 UTC, str4d approved these changes
Re-utACK

2023-03-13 17:51 UTC, merged

2023-03-13 19:02 UTC, daira reviewed
Post-hoc re-ACK