Update ed25519-zebra to 4.0.0.
zcash/zcash pull request #6717
Opened 2023-06-15 18:49 UTC by nuttycom

This deduplicates sha2, rand-core, block-buffer, digest, and ahash. (It adds duplications for hashbrown and libm which are less important.)

2023-06-15 18:50 UTC, nuttycom commented
Subsumes #6705, #6708

2023-06-15 19:06 UTC, str4d requested changes

2023-06-15 19:06 UTC, str4d commented on qa/supply-chain/audits.toml
> +
I am not comfortable with including this audit, as it does not meet the [`safe-to-deploy` standard](https://mozilla.github.io/cargo-vet/built-in-criteria.html#safe-to-deploy) (by virtue of the unsafe blocks not having been fully reviewed). We might want to introduce a mid-point standard of review (that implies `safe-to-run` and is implied by `safe-to-deploy`) that can be used when we don't have time for a full `unsafe` / powerful capability audit. But for now we should remove this and replace it with an exemption.
```suggestion
```

2023-06-15 21:48 UTC, daira approved these changes
utACK

2023-06-16 17:19 UTC, str4d approved these changes
utACK 5edacdf68e36fb4249017ddd72b0f135e92b2742

2023-06-16 17:19 UTC, merged