getinfo rpc: add lightwalletddisabled boolean to result
zcash/zcash pull request #6972
Opened 2024-10-29 16:48 UTC by LarryRuane

Let `lightwalletd` easily discover if the `zcashd` it's connected to is configured with the required `lightwalletd=1` configuration option. The new `getinfo` rpc field added by this PR, `lightwalletddisabled`,  is "backward" (disabled instead of enabled) because if this field isn't returned at all (the running `zcashd` doesn't have this commit), `lightwalletd` will receive it as `false` (missing fields get the "default" value), so it will consider everything to be okay (`lightwalletd` will start up). This allows `zcashd` to be updated after `lightwalletd`.

Note that `zebrad` always supports `lightwalletd` (no special configuration option required), so no change is needed there, although, for consistency, we may want to add this field there and have it always return `false` (lightwalletd support is never disabled).

2024-10-31 23:21 UTC, daira commented on src/rpc/misc.cpp
> +    obj.pushKV("lightwalletddisabled", !fExperimentalLightWalletd);
Please document this in the help output.

2024-10-31 23:22 UTC, daira reviewed
Looks good, but please add the new flag to the help for `getinfo`.

2024-12-01 18:38 UTC, LarryRuane commented
Force pushed daira's suggestion (add the new flag to the help), thanks.

Here's an easy way to manually test this change. Note that changing the `lightwalletd` configuration on an existing mainnet system would be disruptive since it requires a reindex. An alternative is to set up a quick regtest configuration (you can copy and paste this into a terminal window):

```bash
rm -rf /tmp/zrtest
mkdir /tmp/zrtest
cat <<EOF >/tmp/zrtest/zcash.conf
regtest=1
lightwalletd=1
experimentalfeatures=1
debug=1
EOF
src/zcashd -daemon -datadir=/tmp/zrtest
sleep 8
src/zcash-cli -datadir=/tmp/zrtest help getinfo
src/zcash-cli -datadir=/tmp/zrtest getinfo
src/zcash-cli -datadir=/tmp/zrtest stop
```
Check the help output, and verify that you see `"lightwalletddisabled": false,`. Run this again without the `lightwalletd=` line (or set value to 0 instead of 1), and it should report `"lightwalletddisabled": true`

2024-12-06 17:51 UTC, LarryRuane commented
The CI failures here don't seem to have anything to do with the changes in this PR. Should I try to re-run CI, if that's possible?

2025-04-07 15:30 UTC, str4d requested changes
NACK

2025-04-07 15:30 UTC, str4d commented on src/rpc/misc.cpp
> +            "  \"lightwalletddisabled\": true|false  (boolean) true if the configuration does not include the lightwalletd extensions\n"
This PR violates the documented nature of this API:
```
 * @note Do not add or change anything in the information returned by this
 * method. `getinfo` exists for backwards-compatibility only. It combines
 * information from wildly different sources in the program, which is a mess,
 * and is thus planned to be deprecated eventually.
```

If we want to expose what indices are configured, we should do so in a different method (I'd prefer a `zcashd`-specific method personally as this is very `zcashd`-specific).

2025-04-07 15:35 UTC, str4d commented
> The new `getinfo` rpc field added by this PR, `lightwalletddisabled`, is "backward" (disabled instead of enabled) because if this field isn't returned at all (the running `zcashd` doesn't have this commit), `lightwalletd` will receive it as `false` (missing fields get the "default" value)

I disagree with this rationale. There are multiple places in the JSON-RPC where "field is omitted" is a distinct state from "field is provided as false / some default", and `lightwalletd` should not be aliasing those two states. `lightwalletd` needs to be altered to react to the new field, so its behaviour can be changed to whatever is necessary to correctly react to its form. For similar reasons, the field can go into a suitable JSON-RPC method rather than being placed in `getinfo`.

2025-04-15 17:16 UTC, LarryRuane commented
Thanks, @str4d, I understand and agree with both of your comments. I'm inclined now to close the PR, because the remaining lifetimes of both `zcashd` and `lightwalletd` are limited. This isn't an important improvement anyway, it was just to provide a better error message when attempting to use an under-configured `zcashd` (one that doesn't have the required indices enabled). No `lightwalletd` user requested this; it was just something I noticed on my own.

What do you think? Feel free to close this if you agree (or I can). Otherwise, if you do think this is still worth doing, I could make the necessary changes (they wouldn't be difficult).

2025-05-01 20:09 UTC, closed without merging

2025-05-01 20:09 UTC, LarryRuane commented
Closing, see the most recent comment above for the reason.